org.gradle.jvmargs=-Xmx16G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
archives_base_name=applied-experienced
maven_group=es.degrassi
minecraft_version_range=[1.21, 1.22)
neo_version=21.1.199
neo_version_range=[21.1.199,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=appex
mod_version=1.3.2
mod_name=Applied Experienced
mod_description=An Applied Energistics 2 addon that integrates Experience.
icon=icon.png
mod_authors=Alec_016GG
mod_url=https://www.curseforge.com/minecraft/mc-mods/applied-experienced/
mod_github=https://github.com/alec016/Applied-Experienced
mod_issues=https://github.com/alec016/Applied-Experienced/issues
mod_license=GNU Lesser General Public License v3.0
pack_format_number=18

## Dependencies
experiencelib_version=1.2.1
ae2_version=19.2.10
guideme_version=21.1.1
jei_version=19.25.0.322
emi_version=1.1.22
kubejs_version=2101.7.2-build.277
jade_version=6291517
top_version=1.21_neo-12.0.4-6
mekanism_version=1.21.1-10.7.16.82
lombok_version=1.18.34
ae2_jei_integration_version=5748513

# Experience fluid mods by default
MGU=6516546
IF=6502376
titanium=6443608